services:
  postgres:
    image: postgres:16-alpine
    container_name: blog-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks: 
      - backend

volumes:
  pgdata:

networks:
  backend:
